version: '3'

services:
  nginx:
    container_name: speed-test-webapp
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10206:80"
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
